FROM ubuntu:latest

# This dockerfile capabable  of the the minumum required
# to run the tests and nothing else.

MAINTAINER support@influxdb.com

RUN apt-get update && apt-get install -y \
    wget \
    git \
    mercurial \
    build-essential \
    autoconf \
    automake \
    libtool \
    python-setuptools \
    zip \
    curl

# Install protobuf3
ADD install-deps.sh /tmp/
RUN INSTALL_PREFIX=/usr /tmp/install-deps.sh
RUN rm /tmp/install-deps.sh

# Setup env
ENV GOPATH /root/go
ENV PROJECT_DIR $GOPATH/src/github.com/influxdata/kapacitor
ENV PATH $GOPATH/bin:$PATH
RUN mkdir -p $PROJECT_DIR

VOLUME $PROJECT_DIR


# Install go
ENV GO_VERSION 1.4.3
ENV GO_ARCH amd64
RUN wget https://storage.googleapis.com/golang/go${GO_VERSION}.linux-${GO_ARCH}.tar.gz; \
   tar -C /usr/local/ -xf /go${GO_VERSION}.linux-${GO_ARCH}.tar.gz ; \
   rm /go${GO_VERSION}.linux-${GO_ARCH}.tar.gz

# Clone Go tip for compilation
ENV GOROOT_BOOTSTRAP /usr/local/go
RUN git clone https://go.googlesource.com/go
ENV PATH /go/bin:$PATH


# Add script for compiling go
ENV GO_CHECKOUT master
ADD ./gobuild.sh /gobuild.sh
ENTRYPOINT [ "/gobuild.sh" ]
