FROM quay.io/influxdb/cross-builder:go1.24.11-latest

# This dockerfile is capabable of performing all
# build/test/package/deploy actions needed for Kapacitor.

MAINTAINER support@influxdb.com

ADD ./scripts/debian-deps.sh /usr/local/bin/debian-deps.sh

RUN /usr/local/bin/debian-deps.sh

# Need to keep this for generators and similar that may reference only `python` and not `python3`
RUN update-alternatives --install /usr/bin/python python /usr/bin/python3 10

RUN gem install dotenv -v 2.8.1 && gem install fpm

ENV PROJECT_DIR=/kapacitor
RUN mkdir -p $PROJECT_DIR
WORKDIR $PROJECT_DIR

RUN rm /usr/local/bin/debian-deps.sh

# Configure local git
RUN git config --global --add safe.directory $PROJECT_DIR
RUN git config --global user.email "support@influxdb.com"
RUN git config --global user.Name "Docker Builder"

ENTRYPOINT [ "/kapacitor/build.py" ]
