required = [
    "github.com/benbjohnson/tmpl",
    "github.com/golang/protobuf/protoc-gen-go",
    "github.com/mailru/easyjson/easyjson",
]

[prune]
  unused-packages = true
  go-tests = true
  non-go = true

[[constraint]]
  branch = "master"
  name = "github.com/davecgh/go-spew"

[[constraint]]
  branch = "master"
  name = "github.com/mailru/easyjson"

[[constraint]]
  branch = "master"
  name = "github.com/evanphx/json-patch"

[[constraint]]
  branch = "master"
  name = "github.com/ghodss/yaml"

[[constraint]]
  branch = "master"
  name = "github.com/google/uuid"

[[constraint]]
  name = "github.com/influxdata/influxdb"
  version = "~1.1.0"

[[constraint]]
  branch = "master"
  name = "github.com/mitchellh/mapstructure"

[[constraint]]
  branch = "logger-targetmanager-wait"
  name = "github.com/prometheus/prometheus"
  source = "github.com/goller/prometheus"

[[constraint]]
  branch = "master"
  name = "github.com/shurcooL/markdownfmt"

[[constraint]]
  name = "github.com/eclipse/paho.mqtt.golang"
  version = "~1.0.0"

[[constraint]]
  name = "github.com/gorhill/cronexpr"
  branch = "master"

# Pin BurntSushi/toml to the same version used in influxdb
# This also avoids using a version with the WTFPL license
[[constraint]]
  name= "github.com/BurntSushi/toml"
  revision = "a368813c5e648fee92e5f6c30e3944ff9d5e8895"

# Force the Azure projects to be a specific older version that Prometheus needs
[[override]]
  name = "github.com/Azure/azure-sdk-for-go"
  revision = "bd73d950fa4440dae889bd9917bff7cef539f86e"

[[override]]
  name = "github.com/Azure/go-autorest"
  revision = "a2fdd780c9a50455cecd249b00bdc3eb73a78e31"

[[override]]
  name= "gopkg.in/fsnotify.v1"
  revision = "629574ca2a5df945712d3079857300b5e4da0236"
  source = "git@github.com:fsnotify/fsnotify"

[[override]]
  name= "github.com/mailru/easyjson"
  revision = "3fdea8d05856a0c8df22ed4bc71b3219245e4485"
