// Generated by tmpl
// https://github.com/benbjohnson/tmpl
//
// DO NOT EDIT!
// Source: circularqueue.gen.go.tmpl

//lint:file-ignore U1000 this is generated code
package kapacitor

// CircularQueue defines a circular queue, always use the contructor to create one.
type srcPointCircularQueue struct {
	data    []srcPoint
	head    int
	tail    int
	l       int
	oldHead int
}

// newSrcPointconstructs a Circular Queue
// with a given buffer buf.  It is ok for buf to be nil.
func newSrcPointCircularQueue(buf ...srcPoint) *srcPointCircularQueue {
	return &srcPointCircularQueue{
		data:    buf[:cap(buf)],
		head:    0,
		tail:    len(buf),
		l:       len(buf),
		oldHead: -1, // -1 means there is no oldHead
	}
}

// Enqueue adds an item to the queue if you call this it may overwrite any dequeued items,
//so view them via `.Val()` before Enqueuing if you want to use the value.
func (q *srcPointCircularQueue) Enqueue(v srcPoint) {
	// if full we must grow and insert together. This is an expensive op
	if cap(q.data) > q.l { // no need to grow
		if q.tail == len(q.data) {
			q.tail = 0
		}
		q.data[q.tail] = v
	} else {
		if q.tail > q.head { // where the current buffer is filled with continuous data
			buf := make([]srcPoint, cap(q.data)*2)
			copy(buf[:q.tail], q.data[:q.tail])
			copy(buf[q.tail+1:], q.data[q.tail:])
			buf[q.tail] = v
		}
	}
	q.l++
	q.tail++

	// wrap tail
	if q.tail == len(q.data)+1 {
		q.tail = 0
		return
	}
	return
}

// Next moves the head forward, and dequeues it.
func (q *srcPointCircularQueue) Next() bool {

	// zero the old q.head to prevent leaking of sub fields.
	var fill srcPoint
	if q.oldHead >= 0 {
		q.data[q.oldHead] = fill
	}
	q.oldHead = q.head

	// check for empty
	if q.head == q.tail {
		q.oldHead = -1
		return false
	}
	q.l--
	q.head++

	// wrap head if needed
	if q.head == len(q.data)+1 {
		q.head = 0
	}

	return true
}

// Val accesses the item in the queue.  If Next has not been called, it will panic.
func (q *srcPointCircularQueue) Val() srcPoint {
	return q.data[q.head-1]
}

// Peek looks at the queue without dequeueing.
func (q *srcPointCircularQueue) Peek(i int) (srcPoint, bool) {

	if i > q.l-1 {
		var x srcPoint
		return x, false
	}
	p := q.head + i
	if p >= len(q.data) {
		p -= len(q.data)
	}
	return q.data[p], true
}

// Len returns the current number of items in the queue.
func (q *srcPointCircularQueue) Len() int {
	return q.l
}

// CircularQueue defines a circular queue, always use the contructor to create one.
type joinsetPtrCircularQueue struct {
	data    []joinsetPtr
	head    int
	tail    int
	l       int
	oldHead int
}

// newJoinsetPtrconstructs a Circular Queue
// with a given buffer buf.  It is ok for buf to be nil.
func newJoinsetPtrCircularQueue(buf ...joinsetPtr) *joinsetPtrCircularQueue {
	return &joinsetPtrCircularQueue{
		data:    buf[:cap(buf)],
		head:    0,
		tail:    len(buf),
		l:       len(buf),
		oldHead: -1, // -1 means there is no oldHead
	}
}

// Enqueue adds an item to the queue if you call this it may overwrite any dequeued items,
//so view them via `.Val()` before Enqueuing if you want to use the value.
func (q *joinsetPtrCircularQueue) Enqueue(v joinsetPtr) {
	// if full we must grow and insert together. This is an expensive op
	if cap(q.data) > q.l { // no need to grow
		if q.tail == len(q.data) {
			q.tail = 0
		}
		q.data[q.tail] = v
	} else {
		if q.tail > q.head { // where the current buffer is filled with continuous data
			buf := make([]joinsetPtr, cap(q.data)*2)
			copy(buf[:q.tail], q.data[:q.tail])
			copy(buf[q.tail+1:], q.data[q.tail:])
			buf[q.tail] = v
		}
	}
	q.l++
	q.tail++

	// wrap tail
	if q.tail == len(q.data)+1 {
		q.tail = 0
		return
	}
	return
}

// Next moves the head forward, and dequeues it.
func (q *joinsetPtrCircularQueue) Next() bool {

	// zero the old q.head to prevent leaking of sub fields.
	var fill joinsetPtr
	if q.oldHead >= 0 {
		q.data[q.oldHead] = fill
	}
	q.oldHead = q.head

	// check for empty
	if q.head == q.tail {
		q.oldHead = -1
		return false
	}
	q.l--
	q.head++

	// wrap head if needed
	if q.head == len(q.data)+1 {
		q.head = 0
	}

	return true
}

// Val accesses the item in the queue.  If Next has not been called, it will panic.
func (q *joinsetPtrCircularQueue) Val() joinsetPtr {
	return q.data[q.head-1]
}

// Peek looks at the queue without dequeueing.
func (q *joinsetPtrCircularQueue) Peek(i int) (joinsetPtr, bool) {

	if i > q.l-1 {
		var x joinsetPtr
		return x, false
	}
	p := q.head + i
	if p >= len(q.data) {
		p -= len(q.data)
	}
	return q.data[p], true
}

// Len returns the current number of items in the queue.
func (q *joinsetPtrCircularQueue) Len() int {
	return q.l
}
