// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.2
// source: udf.proto

package agent

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EdgeType int32

const (
	EdgeType_STREAM EdgeType = 0
	EdgeType_BATCH  EdgeType = 1
)

// Enum value maps for EdgeType.
var (
	EdgeType_name = map[int32]string{
		0: "STREAM",
		1: "BATCH",
	}
	EdgeType_value = map[string]int32{
		"STREAM": 0,
		"BATCH":  1,
	}
)

func (x EdgeType) Enum() *EdgeType {
	p := new(EdgeType)
	*p = x
	return p
}

func (x EdgeType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EdgeType) Descriptor() protoreflect.EnumDescriptor {
	return file_udf_proto_enumTypes[0].Descriptor()
}

func (EdgeType) Type() protoreflect.EnumType {
	return &file_udf_proto_enumTypes[0]
}

func (x EdgeType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EdgeType.Descriptor instead.
func (EdgeType) EnumDescriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{0}
}

type ValueType int32

const (
	ValueType_BOOL     ValueType = 0
	ValueType_INT      ValueType = 1
	ValueType_DOUBLE   ValueType = 2
	ValueType_STRING   ValueType = 3
	ValueType_DURATION ValueType = 4
)

// Enum value maps for ValueType.
var (
	ValueType_name = map[int32]string{
		0: "BOOL",
		1: "INT",
		2: "DOUBLE",
		3: "STRING",
		4: "DURATION",
	}
	ValueType_value = map[string]int32{
		"BOOL":     0,
		"INT":      1,
		"DOUBLE":   2,
		"STRING":   3,
		"DURATION": 4,
	}
)

func (x ValueType) Enum() *ValueType {
	p := new(ValueType)
	*p = x
	return p
}

func (x ValueType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ValueType) Descriptor() protoreflect.EnumDescriptor {
	return file_udf_proto_enumTypes[1].Descriptor()
}

func (ValueType) Type() protoreflect.EnumType {
	return &file_udf_proto_enumTypes[1]
}

func (x ValueType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ValueType.Descriptor instead.
func (ValueType) EnumDescriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{1}
}

// Request that the process return information about available Options.
type InfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoRequest) Reset() {
	*x = InfoRequest{}
	mi := &file_udf_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoRequest) ProtoMessage() {}

func (x *InfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoRequest.ProtoReflect.Descriptor instead.
func (*InfoRequest) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{0}
}

type InfoResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Wants         EdgeType               `protobuf:"varint,1,opt,name=wants,proto3,enum=agent.EdgeType" json:"wants,omitempty"`
	Provides      EdgeType               `protobuf:"varint,2,opt,name=provides,proto3,enum=agent.EdgeType" json:"provides,omitempty"`
	Options       map[string]*OptionInfo `protobuf:"bytes,3,rep,name=options,proto3" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InfoResponse) Reset() {
	*x = InfoResponse{}
	mi := &file_udf_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoResponse) ProtoMessage() {}

func (x *InfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoResponse.ProtoReflect.Descriptor instead.
func (*InfoResponse) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{1}
}

func (x *InfoResponse) GetWants() EdgeType {
	if x != nil {
		return x.Wants
	}
	return EdgeType_STREAM
}

func (x *InfoResponse) GetProvides() EdgeType {
	if x != nil {
		return x.Provides
	}
	return EdgeType_STREAM
}

func (x *InfoResponse) GetOptions() map[string]*OptionInfo {
	if x != nil {
		return x.Options
	}
	return nil
}

type OptionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ValueTypes    []ValueType            `protobuf:"varint,1,rep,packed,name=valueTypes,proto3,enum=agent.ValueType" json:"valueTypes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionInfo) Reset() {
	*x = OptionInfo{}
	mi := &file_udf_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionInfo) ProtoMessage() {}

func (x *OptionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionInfo.ProtoReflect.Descriptor instead.
func (*OptionInfo) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{2}
}

func (x *OptionInfo) GetValueTypes() []ValueType {
	if x != nil {
		return x.ValueTypes
	}
	return nil
}

// Request that the process initialize itself with the provided options.
type InitRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []*Option              `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"`
	TaskID        string                 `protobuf:"bytes,2,opt,name=taskID,proto3" json:"taskID,omitempty"`
	NodeID        string                 `protobuf:"bytes,3,opt,name=nodeID,proto3" json:"nodeID,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitRequest) Reset() {
	*x = InitRequest{}
	mi := &file_udf_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitRequest) ProtoMessage() {}

func (x *InitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitRequest.ProtoReflect.Descriptor instead.
func (*InitRequest) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{3}
}

func (x *InitRequest) GetOptions() []*Option {
	if x != nil {
		return x.Options
	}
	return nil
}

func (x *InitRequest) GetTaskID() string {
	if x != nil {
		return x.TaskID
	}
	return ""
}

func (x *InitRequest) GetNodeID() string {
	if x != nil {
		return x.NodeID
	}
	return ""
}

type Option struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Values        []*OptionValue         `protobuf:"bytes,2,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Option) Reset() {
	*x = Option{}
	mi := &file_udf_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Option) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Option) ProtoMessage() {}

func (x *Option) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Option.ProtoReflect.Descriptor instead.
func (*Option) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{4}
}

func (x *Option) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Option) GetValues() []*OptionValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type OptionValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Type  ValueType              `protobuf:"varint,1,opt,name=type,proto3,enum=agent.ValueType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*OptionValue_BoolValue
	//	*OptionValue_IntValue
	//	*OptionValue_DoubleValue
	//	*OptionValue_StringValue
	//	*OptionValue_DurationValue
	Value         isOptionValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OptionValue) Reset() {
	*x = OptionValue{}
	mi := &file_udf_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OptionValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OptionValue) ProtoMessage() {}

func (x *OptionValue) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OptionValue.ProtoReflect.Descriptor instead.
func (*OptionValue) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{5}
}

func (x *OptionValue) GetType() ValueType {
	if x != nil {
		return x.Type
	}
	return ValueType_BOOL
}

func (x *OptionValue) GetValue() isOptionValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *OptionValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*OptionValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *OptionValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*OptionValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *OptionValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*OptionValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *OptionValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*OptionValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *OptionValue) GetDurationValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*OptionValue_DurationValue); ok {
			return x.DurationValue
		}
	}
	return 0
}

type isOptionValue_Value interface {
	isOptionValue_Value()
}

type OptionValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,2,opt,name=boolValue,proto3,oneof"`
}

type OptionValue_IntValue struct {
	IntValue int64 `protobuf:"varint,3,opt,name=intValue,proto3,oneof"`
}

type OptionValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,4,opt,name=doubleValue,proto3,oneof"`
}

type OptionValue_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=stringValue,proto3,oneof"`
}

type OptionValue_DurationValue struct {
	DurationValue int64 `protobuf:"varint,6,opt,name=durationValue,proto3,oneof"`
}

func (*OptionValue_BoolValue) isOptionValue_Value() {}

func (*OptionValue_IntValue) isOptionValue_Value() {}

func (*OptionValue_DoubleValue) isOptionValue_Value() {}

func (*OptionValue_StringValue) isOptionValue_Value() {}

func (*OptionValue_DurationValue) isOptionValue_Value() {}

// Respond to Kapacitor whether initialization was successful.
type InitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InitResponse) Reset() {
	*x = InitResponse{}
	mi := &file_udf_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InitResponse) ProtoMessage() {}

func (x *InitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InitResponse.ProtoReflect.Descriptor instead.
func (*InitResponse) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{6}
}

func (x *InitResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *InitResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request that the process provide a snapshot of its state.
type SnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotRequest) Reset() {
	*x = SnapshotRequest{}
	mi := &file_udf_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotRequest) ProtoMessage() {}

func (x *SnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotRequest.ProtoReflect.Descriptor instead.
func (*SnapshotRequest) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{7}
}

// Respond to Kapacitor with a serialized snapshot of the running state.
type SnapshotResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      []byte                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SnapshotResponse) Reset() {
	*x = SnapshotResponse{}
	mi := &file_udf_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotResponse) ProtoMessage() {}

func (x *SnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotResponse.ProtoReflect.Descriptor instead.
func (*SnapshotResponse) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{8}
}

func (x *SnapshotResponse) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Request that the process restore its state from a snapshot.
type RestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Snapshot      []byte                 `protobuf:"bytes,1,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreRequest) Reset() {
	*x = RestoreRequest{}
	mi := &file_udf_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreRequest) ProtoMessage() {}

func (x *RestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreRequest.ProtoReflect.Descriptor instead.
func (*RestoreRequest) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{9}
}

func (x *RestoreRequest) GetSnapshot() []byte {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

// Respond with success or failure to a RestoreRequest
type RestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreResponse) Reset() {
	*x = RestoreResponse{}
	mi := &file_udf_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreResponse) ProtoMessage() {}

func (x *RestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreResponse.ProtoReflect.Descriptor instead.
func (*RestoreResponse) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{10}
}

func (x *RestoreResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RestoreResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Request that the process respond with a Keepalive to verify it is responding.
type KeepaliveRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of nanoseconds since the epoch.
	// Used only for debugging keepalive requests.
	Time          int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveRequest) Reset() {
	*x = KeepaliveRequest{}
	mi := &file_udf_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveRequest) ProtoMessage() {}

func (x *KeepaliveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveRequest.ProtoReflect.Descriptor instead.
func (*KeepaliveRequest) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{11}
}

func (x *KeepaliveRequest) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// Respond to KeepaliveRequest
type KeepaliveResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The number of nanoseconds since the epoch.
	// Used only for debugging keepalive requests.
	Time          int64 `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeepaliveResponse) Reset() {
	*x = KeepaliveResponse{}
	mi := &file_udf_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeepaliveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeepaliveResponse) ProtoMessage() {}

func (x *KeepaliveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeepaliveResponse.ProtoReflect.Descriptor instead.
func (*KeepaliveResponse) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{12}
}

func (x *KeepaliveResponse) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

// Sent from the process to Kapacitor indicating an error has occurred.
// If an ErrorResponse is received, Kapacitor will terminate the process.
type ErrorResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Error         string                 `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorResponse) Reset() {
	*x = ErrorResponse{}
	mi := &file_udf_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorResponse) ProtoMessage() {}

func (x *ErrorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorResponse.ProtoReflect.Descriptor instead.
func (*ErrorResponse) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{13}
}

func (x *ErrorResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

// Indicates the beginning of a batch.
// All subsequent points should be considered
// part of the batch until EndBatch arrives.
// This includes grouping. Batches of
// differing groups may not be interleaved.
//
// All the meta data but tmax is provided,
// since tmax may not be known at
// the beginning of a batch.
//
// Size is the number of points in the batch.
// If size is 0 then the batch has an undetermined size.
type BeginBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,3,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Size          int64                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	ByName        bool                   `protobuf:"varint,5,opt,name=byName,proto3" json:"byName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BeginBatch) Reset() {
	*x = BeginBatch{}
	mi := &file_udf_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginBatch) ProtoMessage() {}

func (x *BeginBatch) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginBatch.ProtoReflect.Descriptor instead.
func (*BeginBatch) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{14}
}

func (x *BeginBatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BeginBatch) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *BeginBatch) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *BeginBatch) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *BeginBatch) GetByName() bool {
	if x != nil {
		return x.ByName
	}
	return false
}

// Message containing information about a single data point.
// Can be sent on it's own or bookended by BeginBatch and EndBatch messages.
type Point struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Time            int64                  `protobuf:"varint,1,opt,name=time,proto3" json:"time,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Database        string                 `protobuf:"bytes,3,opt,name=database,proto3" json:"database,omitempty"`
	RetentionPolicy string                 `protobuf:"bytes,4,opt,name=retentionPolicy,proto3" json:"retentionPolicy,omitempty"`
	Group           string                 `protobuf:"bytes,5,opt,name=group,proto3" json:"group,omitempty"`
	Dimensions      []string               `protobuf:"bytes,6,rep,name=dimensions,proto3" json:"dimensions,omitempty"`
	Tags            map[string]string      `protobuf:"bytes,7,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FieldsDouble    map[string]float64     `protobuf:"bytes,8,rep,name=fieldsDouble,proto3" json:"fieldsDouble,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"fixed64,2,opt,name=value"`
	FieldsInt       map[string]int64       `protobuf:"bytes,9,rep,name=fieldsInt,proto3" json:"fieldsInt,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	FieldsString    map[string]string      `protobuf:"bytes,10,rep,name=fieldsString,proto3" json:"fieldsString,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	FieldsBool      map[string]bool        `protobuf:"bytes,12,rep,name=fieldsBool,proto3" json:"fieldsBool,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	ByName          bool                   `protobuf:"varint,11,opt,name=byName,proto3" json:"byName,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Point) Reset() {
	*x = Point{}
	mi := &file_udf_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Point) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Point) ProtoMessage() {}

func (x *Point) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Point.ProtoReflect.Descriptor instead.
func (*Point) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{15}
}

func (x *Point) GetTime() int64 {
	if x != nil {
		return x.Time
	}
	return 0
}

func (x *Point) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Point) GetDatabase() string {
	if x != nil {
		return x.Database
	}
	return ""
}

func (x *Point) GetRetentionPolicy() string {
	if x != nil {
		return x.RetentionPolicy
	}
	return ""
}

func (x *Point) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *Point) GetDimensions() []string {
	if x != nil {
		return x.Dimensions
	}
	return nil
}

func (x *Point) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *Point) GetFieldsDouble() map[string]float64 {
	if x != nil {
		return x.FieldsDouble
	}
	return nil
}

func (x *Point) GetFieldsInt() map[string]int64 {
	if x != nil {
		return x.FieldsInt
	}
	return nil
}

func (x *Point) GetFieldsString() map[string]string {
	if x != nil {
		return x.FieldsString
	}
	return nil
}

func (x *Point) GetFieldsBool() map[string]bool {
	if x != nil {
		return x.FieldsBool
	}
	return nil
}

func (x *Point) GetByName() bool {
	if x != nil {
		return x.ByName
	}
	return false
}

// Indicates the end of a batch and contains
// all meta data associated with the batch.
// The same meta information is provided for
// ease of use with the addition of tmax since it
// may not be know at BeginBatch.
type EndBatch struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Group         string                 `protobuf:"bytes,2,opt,name=group,proto3" json:"group,omitempty"`
	Tmax          int64                  `protobuf:"varint,3,opt,name=tmax,proto3" json:"tmax,omitempty"`
	Tags          map[string]string      `protobuf:"bytes,4,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ByName        bool                   `protobuf:"varint,5,opt,name=byName,proto3" json:"byName,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndBatch) Reset() {
	*x = EndBatch{}
	mi := &file_udf_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndBatch) ProtoMessage() {}

func (x *EndBatch) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndBatch.ProtoReflect.Descriptor instead.
func (*EndBatch) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{16}
}

func (x *EndBatch) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EndBatch) GetGroup() string {
	if x != nil {
		return x.Group
	}
	return ""
}

func (x *EndBatch) GetTmax() int64 {
	if x != nil {
		return x.Tmax
	}
	return 0
}

func (x *EndBatch) GetTags() map[string]string {
	if x != nil {
		return x.Tags
	}
	return nil
}

func (x *EndBatch) GetByName() bool {
	if x != nil {
		return x.ByName
	}
	return false
}

// Request message wrapper -- sent from Kapacitor to process
type Request struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Request_Info
	//	*Request_Init
	//	*Request_Keepalive
	//	*Request_Snapshot
	//	*Request_Restore
	//	*Request_Begin
	//	*Request_Point
	//	*Request_End
	Message       isRequest_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_udf_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{17}
}

func (x *Request) GetMessage() isRequest_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Request) GetInfo() *InfoRequest {
	if x != nil {
		if x, ok := x.Message.(*Request_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *Request) GetInit() *InitRequest {
	if x != nil {
		if x, ok := x.Message.(*Request_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *Request) GetKeepalive() *KeepaliveRequest {
	if x != nil {
		if x, ok := x.Message.(*Request_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

func (x *Request) GetSnapshot() *SnapshotRequest {
	if x != nil {
		if x, ok := x.Message.(*Request_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Request) GetRestore() *RestoreRequest {
	if x != nil {
		if x, ok := x.Message.(*Request_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *Request) GetBegin() *BeginBatch {
	if x != nil {
		if x, ok := x.Message.(*Request_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *Request) GetPoint() *Point {
	if x != nil {
		if x, ok := x.Message.(*Request_Point); ok {
			return x.Point
		}
	}
	return nil
}

func (x *Request) GetEnd() *EndBatch {
	if x != nil {
		if x, ok := x.Message.(*Request_End); ok {
			return x.End
		}
	}
	return nil
}

type isRequest_Message interface {
	isRequest_Message()
}

type Request_Info struct {
	// Management requests
	Info *InfoRequest `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type Request_Init struct {
	Init *InitRequest `protobuf:"bytes,2,opt,name=init,proto3,oneof"`
}

type Request_Keepalive struct {
	Keepalive *KeepaliveRequest `protobuf:"bytes,3,opt,name=keepalive,proto3,oneof"`
}

type Request_Snapshot struct {
	Snapshot *SnapshotRequest `protobuf:"bytes,4,opt,name=snapshot,proto3,oneof"`
}

type Request_Restore struct {
	Restore *RestoreRequest `protobuf:"bytes,5,opt,name=restore,proto3,oneof"`
}

type Request_Begin struct {
	// Data flow responses
	Begin *BeginBatch `protobuf:"bytes,16,opt,name=begin,proto3,oneof"`
}

type Request_Point struct {
	Point *Point `protobuf:"bytes,17,opt,name=point,proto3,oneof"`
}

type Request_End struct {
	End *EndBatch `protobuf:"bytes,18,opt,name=end,proto3,oneof"`
}

func (*Request_Info) isRequest_Message() {}

func (*Request_Init) isRequest_Message() {}

func (*Request_Keepalive) isRequest_Message() {}

func (*Request_Snapshot) isRequest_Message() {}

func (*Request_Restore) isRequest_Message() {}

func (*Request_Begin) isRequest_Message() {}

func (*Request_Point) isRequest_Message() {}

func (*Request_End) isRequest_Message() {}

// Response message wrapper -- sent from process to Kapacitor
type Response struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Message:
	//
	//	*Response_Info
	//	*Response_Init
	//	*Response_Keepalive
	//	*Response_Snapshot
	//	*Response_Restore
	//	*Response_Error
	//	*Response_Begin
	//	*Response_Point
	//	*Response_End
	Message       isResponse_Message `protobuf_oneof:"message"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_udf_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_udf_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_udf_proto_rawDescGZIP(), []int{18}
}

func (x *Response) GetMessage() isResponse_Message {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Response) GetInfo() *InfoResponse {
	if x != nil {
		if x, ok := x.Message.(*Response_Info); ok {
			return x.Info
		}
	}
	return nil
}

func (x *Response) GetInit() *InitResponse {
	if x != nil {
		if x, ok := x.Message.(*Response_Init); ok {
			return x.Init
		}
	}
	return nil
}

func (x *Response) GetKeepalive() *KeepaliveResponse {
	if x != nil {
		if x, ok := x.Message.(*Response_Keepalive); ok {
			return x.Keepalive
		}
	}
	return nil
}

func (x *Response) GetSnapshot() *SnapshotResponse {
	if x != nil {
		if x, ok := x.Message.(*Response_Snapshot); ok {
			return x.Snapshot
		}
	}
	return nil
}

func (x *Response) GetRestore() *RestoreResponse {
	if x != nil {
		if x, ok := x.Message.(*Response_Restore); ok {
			return x.Restore
		}
	}
	return nil
}

func (x *Response) GetError() *ErrorResponse {
	if x != nil {
		if x, ok := x.Message.(*Response_Error); ok {
			return x.Error
		}
	}
	return nil
}

func (x *Response) GetBegin() *BeginBatch {
	if x != nil {
		if x, ok := x.Message.(*Response_Begin); ok {
			return x.Begin
		}
	}
	return nil
}

func (x *Response) GetPoint() *Point {
	if x != nil {
		if x, ok := x.Message.(*Response_Point); ok {
			return x.Point
		}
	}
	return nil
}

func (x *Response) GetEnd() *EndBatch {
	if x != nil {
		if x, ok := x.Message.(*Response_End); ok {
			return x.End
		}
	}
	return nil
}

type isResponse_Message interface {
	isResponse_Message()
}

type Response_Info struct {
	// Management responses
	Info *InfoResponse `protobuf:"bytes,1,opt,name=info,proto3,oneof"`
}

type Response_Init struct {
	Init *InitResponse `protobuf:"bytes,2,opt,name=init,proto3,oneof"`
}

type Response_Keepalive struct {
	Keepalive *KeepaliveResponse `protobuf:"bytes,3,opt,name=keepalive,proto3,oneof"`
}

type Response_Snapshot struct {
	Snapshot *SnapshotResponse `protobuf:"bytes,4,opt,name=snapshot,proto3,oneof"`
}

type Response_Restore struct {
	Restore *RestoreResponse `protobuf:"bytes,5,opt,name=restore,proto3,oneof"`
}

type Response_Error struct {
	Error *ErrorResponse `protobuf:"bytes,6,opt,name=error,proto3,oneof"`
}

type Response_Begin struct {
	// Data flow responses
	Begin *BeginBatch `protobuf:"bytes,16,opt,name=begin,proto3,oneof"`
}

type Response_Point struct {
	Point *Point `protobuf:"bytes,17,opt,name=point,proto3,oneof"`
}

type Response_End struct {
	End *EndBatch `protobuf:"bytes,18,opt,name=end,proto3,oneof"`
}

func (*Response_Info) isResponse_Message() {}

func (*Response_Init) isResponse_Message() {}

func (*Response_Keepalive) isResponse_Message() {}

func (*Response_Snapshot) isResponse_Message() {}

func (*Response_Restore) isResponse_Message() {}

func (*Response_Error) isResponse_Message() {}

func (*Response_Begin) isResponse_Message() {}

func (*Response_Point) isResponse_Message() {}

func (*Response_End) isResponse_Message() {}

var File_udf_proto protoreflect.FileDescriptor

const file_udf_proto_rawDesc = "" +
	"\n" +
	"\tudf.proto\x12\x05agent\"\r\n" +
	"\vInfoRequest\"\xed\x01\n" +
	"\fInfoResponse\x12%\n" +
	"\x05wants\x18\x01 \x01(\x0e2\x0f.agent.EdgeTypeR\x05wants\x12+\n" +
	"\bprovides\x18\x02 \x01(\x0e2\x0f.agent.EdgeTypeR\bprovides\x12:\n" +
	"\aoptions\x18\x03 \x03(\v2 .agent.InfoResponse.OptionsEntryR\aoptions\x1aM\n" +
	"\fOptionsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12'\n" +
	"\x05value\x18\x02 \x01(\v2\x11.agent.OptionInfoR\x05value:\x028\x01\">\n" +
	"\n" +
	"OptionInfo\x120\n" +
	"\n" +
	"valueTypes\x18\x01 \x03(\x0e2\x10.agent.ValueTypeR\n" +
	"valueTypes\"f\n" +
	"\vInitRequest\x12'\n" +
	"\aoptions\x18\x01 \x03(\v2\r.agent.OptionR\aoptions\x12\x16\n" +
	"\x06taskID\x18\x02 \x01(\tR\x06taskID\x12\x16\n" +
	"\x06nodeID\x18\x03 \x01(\tR\x06nodeID\"H\n" +
	"\x06Option\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12*\n" +
	"\x06values\x18\x02 \x03(\v2\x12.agent.OptionValueR\x06values\"\xea\x01\n" +
	"\vOptionValue\x12$\n" +
	"\x04type\x18\x01 \x01(\x0e2\x10.agent.ValueTypeR\x04type\x12\x1e\n" +
	"\tboolValue\x18\x02 \x01(\bH\x00R\tboolValue\x12\x1c\n" +
	"\bintValue\x18\x03 \x01(\x03H\x00R\bintValue\x12\"\n" +
	"\vdoubleValue\x18\x04 \x01(\x01H\x00R\vdoubleValue\x12\"\n" +
	"\vstringValue\x18\x05 \x01(\tH\x00R\vstringValue\x12&\n" +
	"\rdurationValue\x18\x06 \x01(\x03H\x00R\rdurationValueB\a\n" +
	"\x05value\">\n" +
	"\fInitResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x11\n" +
	"\x0fSnapshotRequest\".\n" +
	"\x10SnapshotResponse\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\fR\bsnapshot\",\n" +
	"\x0eRestoreRequest\x12\x1a\n" +
	"\bsnapshot\x18\x01 \x01(\fR\bsnapshot\"A\n" +
	"\x0fRestoreResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"&\n" +
	"\x10KeepaliveRequest\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\"'\n" +
	"\x11KeepaliveResponse\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\"%\n" +
	"\rErrorResponse\x12\x14\n" +
	"\x05error\x18\x01 \x01(\tR\x05error\"\xcc\x01\n" +
	"\n" +
	"BeginBatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12/\n" +
	"\x04tags\x18\x03 \x03(\v2\x1b.agent.BeginBatch.TagsEntryR\x04tags\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x03R\x04size\x12\x16\n" +
	"\x06byName\x18\x05 \x01(\bR\x06byName\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa8\x06\n" +
	"\x05Point\x12\x12\n" +
	"\x04time\x18\x01 \x01(\x03R\x04time\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bdatabase\x18\x03 \x01(\tR\bdatabase\x12(\n" +
	"\x0fretentionPolicy\x18\x04 \x01(\tR\x0fretentionPolicy\x12\x14\n" +
	"\x05group\x18\x05 \x01(\tR\x05group\x12\x1e\n" +
	"\n" +
	"dimensions\x18\x06 \x03(\tR\n" +
	"dimensions\x12*\n" +
	"\x04tags\x18\a \x03(\v2\x16.agent.Point.TagsEntryR\x04tags\x12B\n" +
	"\ffieldsDouble\x18\b \x03(\v2\x1e.agent.Point.FieldsDoubleEntryR\ffieldsDouble\x129\n" +
	"\tfieldsInt\x18\t \x03(\v2\x1b.agent.Point.FieldsIntEntryR\tfieldsInt\x12B\n" +
	"\ffieldsString\x18\n" +
	" \x03(\v2\x1e.agent.Point.FieldsStringEntryR\ffieldsString\x12<\n" +
	"\n" +
	"fieldsBool\x18\f \x03(\v2\x1c.agent.Point.FieldsBoolEntryR\n" +
	"fieldsBool\x12\x16\n" +
	"\x06byName\x18\v \x01(\bR\x06byName\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a?\n" +
	"\x11FieldsDoubleEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x01R\x05value:\x028\x01\x1a<\n" +
	"\x0eFieldsIntEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01\x1a?\n" +
	"\x11FieldsStringEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a=\n" +
	"\x0fFieldsBoolEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\"\xc8\x01\n" +
	"\bEndBatch\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05group\x18\x02 \x01(\tR\x05group\x12\x12\n" +
	"\x04tmax\x18\x03 \x01(\x03R\x04tmax\x12-\n" +
	"\x04tags\x18\x04 \x03(\v2\x19.agent.EndBatch.TagsEntryR\x04tags\x12\x16\n" +
	"\x06byName\x18\x05 \x01(\bR\x06byName\x1a7\n" +
	"\tTagsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x80\x03\n" +
	"\aRequest\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x12.agent.InfoRequestH\x00R\x04info\x12(\n" +
	"\x04init\x18\x02 \x01(\v2\x12.agent.InitRequestH\x00R\x04init\x127\n" +
	"\tkeepalive\x18\x03 \x01(\v2\x17.agent.KeepaliveRequestH\x00R\tkeepalive\x124\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x16.agent.SnapshotRequestH\x00R\bsnapshot\x121\n" +
	"\arestore\x18\x05 \x01(\v2\x15.agent.RestoreRequestH\x00R\arestore\x12)\n" +
	"\x05begin\x18\x10 \x01(\v2\x11.agent.BeginBatchH\x00R\x05begin\x12$\n" +
	"\x05point\x18\x11 \x01(\v2\f.agent.PointH\x00R\x05point\x12#\n" +
	"\x03end\x18\x12 \x01(\v2\x0f.agent.EndBatchH\x00R\x03endB\t\n" +
	"\amessage\"\xb4\x03\n" +
	"\bResponse\x12)\n" +
	"\x04info\x18\x01 \x01(\v2\x13.agent.InfoResponseH\x00R\x04info\x12)\n" +
	"\x04init\x18\x02 \x01(\v2\x13.agent.InitResponseH\x00R\x04init\x128\n" +
	"\tkeepalive\x18\x03 \x01(\v2\x18.agent.KeepaliveResponseH\x00R\tkeepalive\x125\n" +
	"\bsnapshot\x18\x04 \x01(\v2\x17.agent.SnapshotResponseH\x00R\bsnapshot\x122\n" +
	"\arestore\x18\x05 \x01(\v2\x16.agent.RestoreResponseH\x00R\arestore\x12,\n" +
	"\x05error\x18\x06 \x01(\v2\x14.agent.ErrorResponseH\x00R\x05error\x12)\n" +
	"\x05begin\x18\x10 \x01(\v2\x11.agent.BeginBatchH\x00R\x05begin\x12$\n" +
	"\x05point\x18\x11 \x01(\v2\f.agent.PointH\x00R\x05point\x12#\n" +
	"\x03end\x18\x12 \x01(\v2\x0f.agent.EndBatchH\x00R\x03endB\t\n" +
	"\amessage*!\n" +
	"\bEdgeType\x12\n" +
	"\n" +
	"\x06STREAM\x10\x00\x12\t\n" +
	"\x05BATCH\x10\x01*D\n" +
	"\tValueType\x12\b\n" +
	"\x04BOOL\x10\x00\x12\a\n" +
	"\x03INT\x10\x01\x12\n" +
	"\n" +
	"\x06DOUBLE\x10\x02\x12\n" +
	"\n" +
	"\x06STRING\x10\x03\x12\f\n" +
	"\bDURATION\x10\x04B\tZ\a.;agentb\x06proto3"

var (
	file_udf_proto_rawDescOnce sync.Once
	file_udf_proto_rawDescData []byte
)

func file_udf_proto_rawDescGZIP() []byte {
	file_udf_proto_rawDescOnce.Do(func() {
		file_udf_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_udf_proto_rawDesc), len(file_udf_proto_rawDesc)))
	})
	return file_udf_proto_rawDescData
}

var file_udf_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_udf_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_udf_proto_goTypes = []any{
	(EdgeType)(0),             // 0: agent.EdgeType
	(ValueType)(0),            // 1: agent.ValueType
	(*InfoRequest)(nil),       // 2: agent.InfoRequest
	(*InfoResponse)(nil),      // 3: agent.InfoResponse
	(*OptionInfo)(nil),        // 4: agent.OptionInfo
	(*InitRequest)(nil),       // 5: agent.InitRequest
	(*Option)(nil),            // 6: agent.Option
	(*OptionValue)(nil),       // 7: agent.OptionValue
	(*InitResponse)(nil),      // 8: agent.InitResponse
	(*SnapshotRequest)(nil),   // 9: agent.SnapshotRequest
	(*SnapshotResponse)(nil),  // 10: agent.SnapshotResponse
	(*RestoreRequest)(nil),    // 11: agent.RestoreRequest
	(*RestoreResponse)(nil),   // 12: agent.RestoreResponse
	(*KeepaliveRequest)(nil),  // 13: agent.KeepaliveRequest
	(*KeepaliveResponse)(nil), // 14: agent.KeepaliveResponse
	(*ErrorResponse)(nil),     // 15: agent.ErrorResponse
	(*BeginBatch)(nil),        // 16: agent.BeginBatch
	(*Point)(nil),             // 17: agent.Point
	(*EndBatch)(nil),          // 18: agent.EndBatch
	(*Request)(nil),           // 19: agent.Request
	(*Response)(nil),          // 20: agent.Response
	nil,                       // 21: agent.InfoResponse.OptionsEntry
	nil,                       // 22: agent.BeginBatch.TagsEntry
	nil,                       // 23: agent.Point.TagsEntry
	nil,                       // 24: agent.Point.FieldsDoubleEntry
	nil,                       // 25: agent.Point.FieldsIntEntry
	nil,                       // 26: agent.Point.FieldsStringEntry
	nil,                       // 27: agent.Point.FieldsBoolEntry
	nil,                       // 28: agent.EndBatch.TagsEntry
}
var file_udf_proto_depIdxs = []int32{
	0,  // 0: agent.InfoResponse.wants:type_name -> agent.EdgeType
	0,  // 1: agent.InfoResponse.provides:type_name -> agent.EdgeType
	21, // 2: agent.InfoResponse.options:type_name -> agent.InfoResponse.OptionsEntry
	1,  // 3: agent.OptionInfo.valueTypes:type_name -> agent.ValueType
	6,  // 4: agent.InitRequest.options:type_name -> agent.Option
	7,  // 5: agent.Option.values:type_name -> agent.OptionValue
	1,  // 6: agent.OptionValue.type:type_name -> agent.ValueType
	22, // 7: agent.BeginBatch.tags:type_name -> agent.BeginBatch.TagsEntry
	23, // 8: agent.Point.tags:type_name -> agent.Point.TagsEntry
	24, // 9: agent.Point.fieldsDouble:type_name -> agent.Point.FieldsDoubleEntry
	25, // 10: agent.Point.fieldsInt:type_name -> agent.Point.FieldsIntEntry
	26, // 11: agent.Point.fieldsString:type_name -> agent.Point.FieldsStringEntry
	27, // 12: agent.Point.fieldsBool:type_name -> agent.Point.FieldsBoolEntry
	28, // 13: agent.EndBatch.tags:type_name -> agent.EndBatch.TagsEntry
	2,  // 14: agent.Request.info:type_name -> agent.InfoRequest
	5,  // 15: agent.Request.init:type_name -> agent.InitRequest
	13, // 16: agent.Request.keepalive:type_name -> agent.KeepaliveRequest
	9,  // 17: agent.Request.snapshot:type_name -> agent.SnapshotRequest
	11, // 18: agent.Request.restore:type_name -> agent.RestoreRequest
	16, // 19: agent.Request.begin:type_name -> agent.BeginBatch
	17, // 20: agent.Request.point:type_name -> agent.Point
	18, // 21: agent.Request.end:type_name -> agent.EndBatch
	3,  // 22: agent.Response.info:type_name -> agent.InfoResponse
	8,  // 23: agent.Response.init:type_name -> agent.InitResponse
	14, // 24: agent.Response.keepalive:type_name -> agent.KeepaliveResponse
	10, // 25: agent.Response.snapshot:type_name -> agent.SnapshotResponse
	12, // 26: agent.Response.restore:type_name -> agent.RestoreResponse
	15, // 27: agent.Response.error:type_name -> agent.ErrorResponse
	16, // 28: agent.Response.begin:type_name -> agent.BeginBatch
	17, // 29: agent.Response.point:type_name -> agent.Point
	18, // 30: agent.Response.end:type_name -> agent.EndBatch
	4,  // 31: agent.InfoResponse.OptionsEntry.value:type_name -> agent.OptionInfo
	32, // [32:32] is the sub-list for method output_type
	32, // [32:32] is the sub-list for method input_type
	32, // [32:32] is the sub-list for extension type_name
	32, // [32:32] is the sub-list for extension extendee
	0,  // [0:32] is the sub-list for field type_name
}

func init() { file_udf_proto_init() }
func file_udf_proto_init() {
	if File_udf_proto != nil {
		return
	}
	file_udf_proto_msgTypes[5].OneofWrappers = []any{
		(*OptionValue_BoolValue)(nil),
		(*OptionValue_IntValue)(nil),
		(*OptionValue_DoubleValue)(nil),
		(*OptionValue_StringValue)(nil),
		(*OptionValue_DurationValue)(nil),
	}
	file_udf_proto_msgTypes[17].OneofWrappers = []any{
		(*Request_Info)(nil),
		(*Request_Init)(nil),
		(*Request_Keepalive)(nil),
		(*Request_Snapshot)(nil),
		(*Request_Restore)(nil),
		(*Request_Begin)(nil),
		(*Request_Point)(nil),
		(*Request_End)(nil),
	}
	file_udf_proto_msgTypes[18].OneofWrappers = []any{
		(*Response_Info)(nil),
		(*Response_Init)(nil),
		(*Response_Keepalive)(nil),
		(*Response_Snapshot)(nil),
		(*Response_Restore)(nil),
		(*Response_Error)(nil),
		(*Response_Begin)(nil),
		(*Response_Point)(nil),
		(*Response_End)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_udf_proto_rawDesc), len(file_udf_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_udf_proto_goTypes,
		DependencyIndexes: file_udf_proto_depIdxs,
		EnumInfos:         file_udf_proto_enumTypes,
		MessageInfos:      file_udf_proto_msgTypes,
	}.Build()
	File_udf_proto = out.File
	file_udf_proto_goTypes = nil
	file_udf_proto_depIdxs = nil
}
